Esta notebook contiene el preprocesamiento de los datos

El modelo debe recibir 3 features: el prefijo(prefix), el input_text y el output text

# Imports

In [ ]:
import pandas as pd

### tapaco dataset

In [ ]:

tapaco_dataset = pd.read_csv("tapaco_paraphrases_dataset.csv",sep="\t")
tapaco_dataset.head()

                      Text           Paraphrase
0        I ate the cheese.        I eat cheese.
1     I'm eating a yogurt.   I'm eating cheese.
2  I'm having some cheese.   I eat some cheese.
3             It's Monday.  It is Monday today.
4       It's Monday today.     Today is Monday.

In [ ]:
# Rename columns
tapaco_dataset.rename(columns={'Text': 'input_text', 'Paraphrase': 'target_text'}, inplace=True)

In [ ]:
# Add prefix column
tapaco_dataset['prefix'] = 'paraphrase'

In [ ]:
# Reorder the columns
tapaco_dataset = tapaco_dataset[['prefix', 'input_text', 'target_text']]
tapaco_dataset.head()

       prefix               input_text          target_text
0  paraphrase        I ate the cheese.        I eat cheese.
1  paraphrase     I'm eating a yogurt.   I'm eating cheese.
2  paraphrase  I'm having some cheese.   I eat some cheese.
3  paraphrase             It's Monday.  It is Monday today.
4  paraphrase       It's Monday today.     Today is Monday.

In [ ]:
# Download csv file
tapaco_dataset.to_csv("datasets/tapaco_dataset.csv", index=False)

### Paws dataset

In [ ]:
paws_dataset = pd.read_csv("paws_dataset.csv", sep=",")
paws_dataset.head()

,Unnamed: 0,id,sentence1,sentence2,label
0,0,1,"In Paris , in October 1560 , he secretly met t...","In October 1560 , he secretly met with the Eng...",0
1,1,2,The NBA season of 1975 -- 76 was the 30th seas...,The 1975 -- 76 season of the National Basketba...,1
2,2,3,"There are also specific discussions , public p...","There are also public discussions , profile sp...",0
3,3,4,When comparable rates of flow can be maintaine...,The results are high when comparable flow rate...,1
4,4,5,It is the seat of Zerendi District in Akmola R...,It is the seat of the district of Zerendi in A...,1

In [ ]:
# Rename columns
paws_dataset.rename(columns={'sentence1': 'input_text', 'sentence2': 'target_text'}, inplace=True)

In [ ]:
# Add prefix and reorder the columns
paws_dataset['prefix'] = 'paraphrase'
paws_dataset = paws_dataset[['prefix', 'input_text', 'target_text']]

In [ ]:
paws_dataset.head()

,prefix,input_text,target_text
0,paraphrase,"In Paris , in October 1560 , he secretly met t...","In October 1560 , he secretly met with the Eng..."
1,paraphrase,The NBA season of 1975 -- 76 was the 30th seas...,The 1975 -- 76 season of the National Basketba...
2,paraphrase,"There are also specific discussions , public p...","There are also public discussions , profile sp..."
3,paraphrase,When comparable rates of flow can be maintaine...,The results are high when comparable flow rate...
4,paraphrase,It is the seat of Zerendi District in Akmola R...,It is the seat of the district of Zerendi in A...

In [ ]:
paws_dataset.to_csv("datasets/paws_dataset.csv", index=False)

### Combine datasets

In [ ]:
result = pd.concat([tapaco_dataset,paws_dataset], ignore_index=True)

In [ ]:
result.shape

(122919, 3)

### Extended dataset

In [ ]:
result.to_csv('datasets/datasets_combine.csv', index=False)

In [ ]:
extended_dataset = pd.read_csv("extended_dataset.csv",sep=",")
extended_dataset.head()

,text,paraphrase
0,Inception is a mind-bending film that explores...,Inception is a thought-provoking movie that de...
1,Stranger Things is a popular TV show that blen...,Stranger Things is a widely-loved television s...
2,The Shawshank Redemption is often hailed as on...,Many consider The Shawshank Redemption to be o...
3,Breaking Bad follows the transformation of a h...,Breaking Bad chronicles the evolution of a hig...
4,The Dark Knight is a superhero film known for ...,The Dark Knight is a superhero movie renowned ...

In [ ]:
extended_dataset.rename(columns={'text': 'input_text', 'paraphrase': 'target_text'}, inplace=True)

In [ ]:
extended_dataset['prefix'] = 'paraphrase'
extended_dataset = extended_dataset[['prefix', 'input_text', 'target_text']]

In [ ]:
extended_dataset.head()

,prefix,input_text,target_text
0,paraphrase,Inception is a mind-bending film that explores...,Inception is a thought-provoking movie that de...
1,paraphrase,Stranger Things is a popular TV show that blen...,Stranger Things is a widely-loved television s...
2,paraphrase,The Shawshank Redemption is often hailed as on...,Many consider The Shawshank Redemption to be o...
3,paraphrase,Breaking Bad follows the transformation of a h...,Breaking Bad chronicles the evolution of a hig...
4,paraphrase,The Dark Knight is a superhero film known for ...,The Dark Knight is a superhero movie renowned ...

In [ ]:
extended_dataset.to_csv("datasets/extended_dataset.csv", index=False)